version: '3.8'

services:
  user-failure-stats:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-failure-stats
    volumes:
      - ./output:/app/output
    environment:
      - DB_URL=${DB_URL}
      - START_DATE=${START_DATE:-2025-05-20 18:30:00}
      - END_DATE=${END_DATE:-2025-05-22 18:29:59}
      - DB_CONNECTION_TIMEOUT=30
      - DB_QUERY_TIMEOUT=60
      - DB_MAX_RETRIES=3
    restart: on-failure 