version: '3.8'

services:
  user-failure-stats:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-failure-stats
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    environment:
      # Database Configuration
      - DB_URL=${DB_URL}
      - DB_CONNECTION_TIMEOUT=30
      - DB_QUERY_TIMEOUT=60
      - DB_MAX_RETRIES=3
      
      # Azure Storage Configuration
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER=user-failure-reports
      
      # Cache Configuration
      - CACHE_DURATION_HOURS=24
      - FORCE_REFRESH=${FORCE_REFRESH:-false}
      
      # Application Configuration
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 